### ISSUE TITLE
running speedseq_setup.py twice does not re-download everything

### ISSUE THREAD

**Issue by ying-w** [cc2qe/speedseq#16]
Would it be possible for speedseq_setup to check pre-existing versions against the version that speedseq is trying to install. Additionally, can you pass a make -j <num_cores> into the make commands or run certain steps in parallel  since installation takes a while.

**Comment by cc2qe** [comment]
we've overhauled the installation process so speedseq_setup.py no longer exists. Additionally make is now modular so you can do "make align" or "make sv" to compile components individually. In my experience the compilation doesn't take long enough to necessitate parallelization.
