### ISSUE TITLE
Generating dicordant and splitter bam file

### ISSUE THREAD

**Issue by rhshah** [cc2qe/speedseq#22]
Hi Colby,

I want to run the speedseq sv functionality on existing bwa-mem produced Tumor/Normal bam file. 

I tried using samblaster to generate this but i always get the splitter bam file as empty. Do you have any suggestions or other ways to quickly get these files. 

Thanks you for your help in advance.

Best,
Ronak

**Comment by cc2qe** [comment]
What aligner were you using? We have only tested samblaster's splitter/discordant extraction on BWA-MEM aligned files (using the -M flag to mark shorter split reads as secondary).

Also, is your BAM file sorted by read ID?

**Comment by rhshah** [comment]
We are using bwa mem (0.7.5a-r405) , yes we do mark them using -M and yes the bam file was read name sorted for samblaster to run. These is the example command:
bwa  mem -t 4 -PM

Thanks for your quick reply.

**Comment by cc2qe** [comment]
Interesting, I'm not sure why that wouldn't work. Could you send me the first 10000 or so lines from your BAM to cc2qe at virginia dot edu? I probably won't have time to look at it until tomorrow at the earliest though.

In the meantime, we have this script that may work on your file:
https://github.com/hall-lab/svtools/blob/master/extractSplitReads_BwaMem

**Comment by cc2qe** [comment]
BAM file lacked secondary reads, potentially due to different behavior of BWA MEM prior to v0.7.7.
closing.

**Comment by xtYao** [comment]
Hi @cc2qe ,

So if the BAM is aligned by `bwa aln` and not sorted by QNAME, then the internal default spl extraction of `speedseq sv` won't work, right?

I noticed the discordant reads were generated properly but not split reads. In contrast, if I explicitly run `speedseq realign` on my BAMs first, then the split reads extraction is successful, but this step also does the entire BAM which is a big waste of time when we are only interested in the reads supporting potential SVs. 

Do you have the plan to make the default behavior of `speedseq sv` to be compatible with `bwa aln` BAMs?

Thanks,
Xiaotong

**Comment by cc2qe** [comment]
Hi Xiaotong,

Yes, that's correct. If you do not use SpeedSeq for alignment, you'll have to generate discordant and split reads. We already have a tool for doing this, called Extract SV Reads. You can find the software and documentation here: https://github.com/hall-lab/extract_sv_reads.

Best,
Colby
