### ISSUE TITLE
error writing all requested bytes to file

### ISSUE THREAD

**Issue by wb223495** [cc2qe/speedseq#23]
Thanks for developing speedseq, I've been using it to call SVs in quads and it usually works except occasionally I get the following error (pasted below). Could you please help resolve this issue? N.b. sometimes I resubmit failed jobs and they work.

Error in <TFile::WriteBuffer>: error writing all requested bytes to file /oasis/tscc/scratch/wb/lumpy/temp/speedseq_sv_74-0115/cnvnator-temp/03C14334-sorted-rmdups-realigned-bqsr.bam.root, wrote 1230 of 4272
Error in <TTree::Fill>: Failed filling branch:7.rd_parity, nbytes=-1, entry=4405788
 This error is symptomatic of a Tree created as a memory-resident Tree Instead of doing:
    TTree *T = new TTree(...)
    TFile *f = new TFile(...) you should do:
    TFile *f = new TFile(...)
    TTree *T = new TTree(...)R__unzip: error -5 in inflate (zlib)
Error in <TBasket::ReadBasketBuffers>: fNbytes = 4272, fKeylen = 73, fObjlen = 31926, noutot = 0, nout=0, nin=4199, nbuf=31
926Error in <TBranch::GetBasket>: File: /oasis/tscc/scratch/wb/lumpy/temp/speedseq_sv_74-0115/cnvnator-temp/03C14334-so
rted-rmdups-realigned-bqsr.bam.root at byte:2721053490, branch:rd_parity, entry:4389825, badread=1, nerrors=1, basketnumber
=275R__unzip: error -5 in inflate (zlib)
Error in <TBasket::ReadBasketBuffers>: fNbytes = 4272, fKeylen = 73, fObjlen = 31926, noutot = 0, nout=0, nin=4199, nbuf=31
926
.
.
.
.
(and so on...)

**Comment by cc2qe** [comment]
hmm, that's interesting. Can you tell me more about your samples and the data you're processing?
- species
- ref genome
- WGS? (depth?)
- number of threads you were running?

I have not seen this error before. I wonder if it's related to our parallelization of CNVnator not agreeing with your filesystem.

**Comment by ryanlayer** [comment]
It looks like it has to do with root, one of the libraries that CNVnator is
built on.  It appears as if you may have run out of room when writing to
the root file.

See: https://root.cern.ch/phpBB3/viewtopic.php?f=3&t=19427&view=unread

On Wed, Apr 8, 2015 at 8:19 AM, Colby Chiang <notifications@github.com>
wrote:

> hmm, that's interesting. Can you tell me more about your samples and the
> data you're processing?
>
>    - species
>    - ref genome
>    - WGS? (depth?)
>    - number of threads you were running?
>
> I have not seen this error before. I wonder if it's related to our
> parallelization of CNVnator not agreeing with your filesystem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cc2qe/speedseq/issues/23#issuecomment-90895867>.
>



-- 
Ryan Layer
