### ISSUE TITLE
installing root for CNVnator

### ISSUE THREAD

**Issue by MinocheAE** [cc2qe/speedseq#27]
Nice pipeline, especially the CNV part! CNVnator gives many valid CNV calls complementary to lumpy. 

When installing root locally for CNVnator, it has to be compiled without prefix, otherwise it won't run through the entire speedseq pipeline (at least for me). I know it is counterintuitive. Just type
./configure
make

no "make install" required. Everything gets compiled locally and with source /pathto/root/bin/thisroot.sh libs gets linked.

**Comment by cc2qe** [comment]
thanks for sharing this, I've added that info to the Troubleshooting part of the README.
